trainPath : '__data__/MADE2-1.0/process2_stepFour_corp'
truthPath : '__data__/MADE2-1.0/process2_stepThree_entity'
weightsPath : 'weights_nodiscard_8000.npy'
vocabPath : 'vocab_nodiscard_8000.pkl'
char_dim : 6
epoch : 30
nclass : -1
outputsize : 19
maxFold : 10
folds : 1
units : 20
batch_size : 100
sent_len : 50
word_len : 10
lstm_act : 'relu'
lstm_loss : 'mean_squared_error'
lstm_opt : 'adam'
use_char : True